version : '3.8'

services:
    mariadb:
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
        args:
          MARIADB_ROOT_PASSWORD : ${MARIADB_ROOT_PASSWORD}
          MARIADB_USER : ${MARIADB_USER}
          MARIADB_USER_PASSWORD : ${MARIADB_USER_PASSWORD}
          SQL_DB_NAME : ${SQL_DB_NAME}
      image: mariadb:inception
      volumes:
        - mariadb_volume:/var/lib/mysql
      networks:
        - inception
      container_name: mariadb
      restart : always
    wordpress:
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
        args:
          MARIADB_USER : ${MARIADB_USER}
          MARIADB_USER_PASSWORD : ${MARIADB_USER_PASSWORD}
          SQL_DB_NAME : ${SQL_DB_NAME}
          WORDPRESS_ADMIN_USER : ${WORDPRESS_ADMIN_USER}
          WORDPRESS_ADMIN_PASSWORD : ${WORDPRESS_ADMIN_PASSWORD}
          WORDPRESS_URL : ${WORDPRESS_URL}
          WORDPRESS_WEBSITE_TITLE : ${WORDPRESS_WEBSITE_TITLE}
          WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      image: wordpress:inception
      depends_on:
        - mariadb
        - redis
      volumes:
        - wordpress_volume:/var/www/wordpress
      networks:
        - inception
      container_name: wordpress
      restart : always
    nginx:
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
        args:
          WORDPRESS_URL : ${WORDPRESS_URL}
          CERTIFICATE_PATH : ${CERTIFICATE_PATH}
          CERTIFICATE_KEY_PATH : ${CERTIFICATE_KEY_PATH}
          STATIC_WEB_URL : ${STATIC_WEB_URL}
          ADMINER_URL: ${ADMINER_URL}
      image: nginx:inception
      depends_on:
        - wordpress
        - static_web
        - adminer
      volumes:
        - wordpress_volume:/var/www/wordpress
      networks:
        - inception
      ports:
        - "443:443"
      container_name: nginx
      restart : always    
    redis:
      build:
        context: ./requirements/bonus/redis
        dockerfile: Dockerfile
        args:
          REDIS_AUTH_PASSWORD : ${REDIS_AUTH_PASSWORD}
      image: redis:inception
      networks:
        - inception
      container_name: redis
      restart : always
    ftp:
      build:
        context: ./requirements/bonus/ftp
        dockerfile: Dockerfile
        args:
          FTP_USER : ${FTP_USER}
          FTP_USER_PASSWORD : ${FTP_USER_PASSWORD}
      image: ftp:inception
      networks:
        - inception
      ports:
        - "21:21"
        - "20:20"
      depends_on:
        - wordpress
      volumes:
        - wordpress_volume:/var/www/wordpress
      container_name: ftp
      restart : always
    static_web:
      build:
        context: ./requirements/bonus/static_web
        dockerfile: Dockerfile
      image: static_web:inception
      networks:
        - inception
      volumes:
        - static_web_volume:/var/static_web
      container_name: static_web
      restart: always
    adminer:
      build:
        context: ./requirements/bonus/adminer
        dockerfile: Dockerfile
      image: adminer:inception
      networks:
        - inception
      container_name: adminer
      restart: always

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  static_web_volume:
      name: static_web_volume
      driver_opts:
        type: none
        device: /home/bamrouch/data/static_web
        o: bind
  mariadb_volume:
    name: mariadb_volume
    driver_opts:
      type: none
      device: /home/bamrouch/data/mariadb
      o: bind
  wordpress_volume:
    name: wordpress_volume
    driver_opts:
      type: none
      device: /home/bamrouch/data/wordpress
      o: bind
